import "./globals.css";
import Header from "@/components/Header";
import Providers from "./Providers";
import Navbar from "@/components/Navbar";
import SearchBox from "@/components/SearchBox";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {/*header*/}
          <Header />
          {/*navbar*/}
          <Navbar />
          {/*searchbox*/}
          <SearchBox />
          {children}
        </Providers>
      </body>
    </html>
  );
}
